const PDFDocument = require('pdfkit');

// Generate comprehensive event report
async function generateEventReport(reportData) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margin: 50,
        info: {
          Title: `${reportData.event.title} - ${reportData.reportType}`,
          Author: 'Evently Management System',
          Subject: `${reportData.reportType} Generated on ${new Date().toLocaleDateString()}`,
          Creator: 'Evently',
          Producer: 'Evently Management System'
        }
      });

      // Add header
      doc.fontSize(24).fillColor('#2c3e50').text(reportData.reportType, 50, 50, { align: 'center' });
      doc.moveDown(20);
      
      // Event Information Section
      doc.fontSize(18).fillColor('#34495e').text('Event Information', 50, 100);
      doc.moveDown(15);
      
      // Event details table
      const eventDetails = [
        ['Event Title:', reportData.event.title],
        ['Description:', reportData.event.description || 'No description provided'],
        ['Start Date:', new Date(reportData.event.start_date).toLocaleDateString()],
        ['End Date:', new Date(reportData.event.end_date).toLocaleDateString()],
        ['Location:', reportData.event.venue || reportData.event.city || 'Online'],
        ['Category:', reportData.event.category || 'Not specified'],
        ['Type:', reportData.event.type || 'Not specified'],
        ['Status:', reportData.event.status || 'Active']
      ];

      let yPos = 130;
      eventDetails.forEach(([label, value]) => {
        doc.fontSize(12).fillColor('#666').text(label, 50, yPos);
        doc.fontSize(12).fillColor('#2c3e50').text(value, 150, yPos);
        yPos += 20;
      });

      doc.moveDown(30);

      // Registration Statistics Section
      doc.fontSize(18).fillColor('#34495e').text('Registration Statistics', 50, yPos);
      doc.moveDown(20);
      yPos += 20;

      const stats = [
        ['Total Registrations:', reportData.totalParticipants.toString()],
        ['Report Generated:', new Date(reportData.generatedAt).toLocaleString()],
        ['Report Type:', reportData.reportType]
      ];

      stats.forEach(([label, value]) => {
        doc.fontSize(12).fillColor('#666').text(label, 50, yPos);
        doc.fontSize(12).fillColor('#2c3e50').text(value, 150, yPos);
        yPos += 20;
      });

      doc.moveDown(30);

      // Participant Details Section
      doc.fontSize(18).fillColor('#34495e').text('Participant Details', 50, yPos);
      doc.moveDown(20);
      yPos += 20;

      // Table headers
      const headers = ['Name', 'Email', 'Registration Date', 'Status'];
      const startX = 50;
      const columnWidths = [150, 200, 120, 80];
      let currentX = startX;

      doc.fontSize(12).fillColor('#34495e');
      headers.forEach((header, index) => {
        doc.text(header, currentX, yPos);
        currentX += columnWidths[index];
      });

      yPos += 20;
      doc.moveDown(10);

      // Draw line under headers
      doc.strokeColor('#ddd').lineWidth(1).moveTo(startX, yPos).lineTo(startX + columnWidths.reduce((a, b) => a + b, 0), yPos).stroke();
      yPos += 15;

      // Participant data
      doc.fontSize(10).fillColor('#666');
      reportData.registrations.forEach((registration) => {
        currentX = startX;
        const rowData = [
          registration.name || 'N/A',
          registration.email || 'N/A',
          new Date(registration.created_at).toLocaleDateString(),
          'Registered'
        ];

        rowData.forEach((data, index) => {
          doc.text(data, currentX, yPos);
          currentX += columnWidths[index];
        });

        yPos += 15;

        // Draw line after each row
        if (yPos < 700) { // Prevent going off page
          doc.strokeColor('#f0f0f0').lineWidth(0.5).moveTo(startX, yPos).lineTo(startX + columnWidths.reduce((a, b) => a + b, 0), yPos).stroke();
          yPos += 5;
        }
      });

      // Footer
      if (yPos > 650) {
        doc.addPage();
      }

      const footerY = doc.page.height - 50;
      doc.fontSize(10).fillColor('#999').text(
        `This report was automatically generated by Evently Management System on ${new Date().toLocaleString()}`,
        50,
        footerY,
        { align: 'center' }
      );

      // Add page numbers
      const totalPages = doc.bufferedPageRange().count;
      doc.fontSize(10).fillColor('#999').text(
        `Page 1 of ${totalPages}`,
        doc.page.width - 50,
        footerY,
        { align: 'right' }
      );

      // Finalize PDF
      const buffers = [];
      doc.on('data', buffers.push.bind(buffers));
      
      doc.on('end', () => {
        const pdfBuffer = Buffer.concat(buffers);
        resolve(pdfBuffer);
      });

      doc.end();

    } catch (error) {
      console.error('Error generating PDF report:', error);
      reject(error);
    }
  });
}

module.exports = {
  generateEventReport
};
