const pool = require("../config/db");
const bcrypt = require("bcrypt");
const jwt = require("jsonwebtoken");
const multer = require("multer");
const path = require("path");

// Configure multer for avatar uploads
const storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, 'uploads/avatars/');
  },
  filename: function (req, file, cb) {
    const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1E9);
    cb(null, 'avatar-' + uniqueSuffix + path.extname(file.originalname));
  }
});

const upload = multer({
  storage: storage,
  limits: {
    fileSize: 5 * 1024 * 1024 // 5MB limit
  },
  fileFilter: function (req, file, cb) {
    // Allow only image files
    if (file.mimetype.startsWith('image/')) {
      cb(null, true);
    } else {
      cb(new Error('Only image files are allowed'), false);
    }
  }
});

// Signup function - Auto-assigns unique ID and checks email uniqueness
exports.signup = async (req, res) => {
  try {
    const { name, email, password } = req.body;

    // Check if email already exists
    const existingUser = await pool.query(
      "SELECT * FROM users WHERE email = $1",
      [email]
    );

    if (existingUser.rows.length > 0) {
      return res.status(409).json({ error: "Email already registered. Please use a different email." });
    }

    // hash password
    const hashedPassword = await bcrypt.hash(password, 10);

    // Insert user - ID is auto-generated by database
    const newUser = await pool.query(
      "INSERT INTO users (name, email, password) VALUES ($1, $2, $3) RETURNING id, name, email, created_at",
      [name, email, hashedPassword]
    );

    res.status(201).json({
      message: "User created successfully",
      user: newUser.rows[0],
    });

  } catch (error) {
    console.error(error);
    res.status(500).json({ error: "Signup failed" });
  }
};

// Login function
exports.login = async (req, res) => {
  try {
    const { email, password } = req.body;

    const user = await pool.query(
      "SELECT * FROM users WHERE email=$1",
      [email]
    );

    if (user.rows.length === 0) {
      return res.status(400).json({ error: "User not found" });
    }

    const validPassword = await bcrypt.compare(
      password,
      user.rows[0].password
    );

    if (!validPassword) {
      return res.status(400).json({ error: "Invalid password" });
    }

    const token = jwt.sign(
      { id: user.rows[0].id },
      process.env.JWT_SECRET,
      { expiresIn: "24h" }
    );

    res.json({
      message: "Login successful",
      token: token,
      user: {
        id: user.rows[0].id,
        name: user.rows[0].name,
        email: user.rows[0].email,
        phone: user.rows[0].phone || '',
        organization: user.rows[0].organization || '',
        role: user.rows[0].role || 'Event Organizer',
        joinDate: user.rows[0].created_at
      }
    });

  } catch (error) {
    console.error(error);
    res.status(500).json({ error: "Login failed" });
  }
};

// Get profile function
exports.getProfile = async (req, res) => {
  try {
    const userId = req.user.id; // From auth middleware

    const user = await pool.query(
      "SELECT id, name, email, avatar, created_at FROM users WHERE id = $1",
      [userId]
    );

    if (user.rows.length === 0) {
      return res.status(404).json({ error: "User not found" });
    }

    // Return user data with phone and organization as empty strings for frontend compatibility
    const userData = user.rows[0];
    res.json({
      id: userData.id,
      name: userData.name,
      email: userData.email,
      avatar: userData.avatar ? `http://localhost:5000/uploads/avatars/${userData.avatar}` : null,
      phone: '',  // Empty since column doesn't exist
      organization: '',  // Empty since column doesn't exist
      role: 'Event Organizer',
      joinDate: userData.created_at
    });

  } catch (error) {
    console.error(error);
    res.status(500).json({ error: "Failed to get profile" });
  }
};

// Change password function
exports.changePassword = async (req, res) => {
  try {
    console.log('Password change request for user:', req.user.id);
    
    const userId = req.user.id; // From auth middleware
    const { currentPassword, newPassword } = req.body;

    // Validate required fields
    if (!currentPassword || !newPassword) {
      return res.status(400).json({ error: "Current password and new password are required" });
    }

    if (newPassword.length < 6) {
      return res.status(400).json({ error: "New password must be at least 6 characters long" });
    }

    // Get user with password
    const user = await pool.query(
      "SELECT * FROM users WHERE id = $1",
      [userId]
    );

    if (user.rows.length === 0) {
      return res.status(404).json({ error: "User not found" });
    }

    // Verify current password
    const validPassword = await bcrypt.compare(
      currentPassword,
      user.rows[0].password
    );

    if (!validPassword) {
      return res.status(400).json({ error: "Current password is incorrect" });
    }

    // Hash new password
    const hashedNewPassword = await bcrypt.hash(newPassword, 10);

    // Update password
    await pool.query(
      "UPDATE users SET password = $1 WHERE id = $2",
      [hashedNewPassword, userId]
    );

    console.log('Password changed successfully for user:', userId);

    res.json({
      message: "Password changed successfully"
    });

  } catch (error) {
    console.error('Password change error:', error);
    res.status(500).json({ error: "Failed to change password: " + error.message });
  }
};
exports.updateProfile = async (req, res) => {
  try {
    console.log('Profile update request:', {
      userId: req.user.id,
      requestBody: req.body
    });

    const userId = req.user.id; // From auth middleware
    const { name, phone, organization } = req.body;

    // Validate required fields
    if (!name || name.trim() === '') {
      return res.status(400).json({ error: "Name is required" });
    }

    // Update user - Only update name since phone and organization columns don't exist
    const updatedUser = await pool.query(
      "UPDATE users SET name = $1 WHERE id = $2 RETURNING id, name, email, created_at",
      [name, userId]
    );

    console.log('Update query result:', updatedUser.rows);

    if (updatedUser.rows.length === 0) {
      return res.status(404).json({ error: "User not found" });
    }

    console.log('Profile updated successfully for user:', userId);

    // Return user data with phone and organization as empty strings for frontend compatibility
    const user = updatedUser.rows[0];
    res.json({
      message: "Profile updated successfully",
      user: {
        id: user.id,
        name: user.name,
        email: user.email,
        phone: phone || '',
        organization: organization || '',
        role: 'Event Organizer',
        joinDate: user.created_at,
        avatar: user.avatar ? `http://localhost:5000/uploads/avatars/${user.avatar}` : null
      }
    });

  } catch (error) {
    console.error('Profile update error:', error);
    res.status(500).json({ error: "Failed to update profile: " + error.message });
  }
};

// Upload avatar function
exports.uploadAvatar = async (req, res) => {
  try {
    const userId = req.user.id; // From auth middleware

    if (!req.file) {
      return res.status(400).json({ error: "No file uploaded" });
    }

    // Update user avatar in database (handle missing column gracefully)
    let updatedUser;
    try {
      updatedUser = await pool.query(
        "UPDATE users SET avatar = $1 WHERE id = $2 RETURNING id, name, email, avatar",
        [req.file.filename, userId]
      );
    } catch (dbError) {
      // If column doesn't exist, add it first
      if (dbError.message.includes('column') && dbError.message.includes('avatar')) {
        console.log('Avatar column missing, adding it...');
        await pool.query('ALTER TABLE users ADD COLUMN avatar VARCHAR(255)');
        
        // Retry the update
        updatedUser = await pool.query(
          "UPDATE users SET avatar = $1 WHERE id = $2 RETURNING id, name, email, avatar",
          [req.file.filename, userId]
        );
      } else {
        throw dbError;
      }
    }

    if (updatedUser.rows.length === 0) {
      return res.status(404).json({ error: "User not found" });
    }

    console.log('Avatar uploaded successfully for user:', userId);

    res.json({
      message: "Profile picture uploaded successfully",
      avatar: `http://localhost:5000/uploads/avatars/${req.file.filename}`
    });

  } catch (error) {
    console.error('Avatar upload error:', error);
    res.status(500).json({ error: "Failed to upload profile picture: " + error.message });
  }
};

// Remove avatar function
exports.removeAvatar = async (req, res) => {
  try {
    const userId = req.user.id; // From auth middleware

    // Get current user to check if they have an avatar
    const currentUser = await pool.query(
      "SELECT avatar FROM users WHERE id = $1",
      [userId]
    );

    if (currentUser.rows.length === 0) {
      return res.status(404).json({ error: "User not found" });
    }

    // Update user avatar to null in database
    await pool.query(
      "UPDATE users SET avatar = NULL WHERE id = $1",
      [userId]
    );

    console.log('Avatar removed successfully for user:', userId);

    res.json({
      message: "Profile picture removed successfully"
    });

  } catch (error) {
    console.error('Avatar removal error:', error);
    res.status(500).json({ error: "Failed to remove profile picture: " + error.message });
  }
};

// Export the upload middleware for use in routes
exports.upload = upload;